name: "Wait For Connection"
description: 'Action to wait for connection from user (condtionally)'
inputs:
  halt-dispatch-input:
    description: 'Should the action wait for user connection from workflow_dispatch?'
    required: false
    default: "no"
runs:
  using: "composite"
  steps:
  - name: Wait for connection (conditionally)
    shell: bash
    env:
      # This variable is on by default, but can be overridden for convenience,
      # in case the workflow calling this action should not be halted, despite
      # other labels/inputs.
      INTERACTIVE_CI: 1
      PYTHONUNBUFFERED: 1
      HALT_DISPATCH_INPUT: ${{ inputs.halt-dispatch-input }}
    run: |
      # Pick an existing Python alias
      python_bin=$(which python3 2>/dev/null || which python)
      # Wait for the connection, if a halt was requested via a label/input
      "$python_bin" "$GITHUB_ACTION_PATH/wait_for_connection.py"
