name: Run Bazel GPU tests using RBE

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        runner: ["arc-linux-x86-g2-96-l4-8gpu"]

    runs-on: ${{ matrix.runner }}
    container:
      image: "gcr.io/tensorflow-testing/nosla-cuda12.3-cudnn9.1-ubuntu20.04-manylinux2014-multipython:latest"

    env:
      JAXCI_USE_DOCKER: 0
      JAXCI_USE_RBE: 1
      JAXCI_RUN_TESTS: 1
      JAXCI_HERMETIC_PYTHON_VERSION: 3.12

    steps:
      - uses: actions/checkout@v3
      # Halt for testing
      - name: Wait For Connection
        uses: ./actions/ci_connection/
      - name: Run Bazel GPU tests using RBE
        env:
          ENV_FILE: ci/envs/run_tests/bazel_rbe
        run: ./ci/run_bazel_test_gpu.sh
