name: Run Bazel CPU tests

# on:
#   pull_request:
#     branches:
#       - main

jobs:
  build:
    strategy:
      matrix:
        runner: ["linux-x86-n2-64"]

    runs-on: ${{ matrix.runner }}
    container:
      image: "us-central1-docker.pkg.dev/tensorflow-sigs/tensorflow/build:670606426-python3.9"

    env:
      # GitHub actions run in Docker by defaut. Disable running the `setup_docker.sh` script.
      JAXCI_SETUP_DOCKER: 0
      # Setup the test environment (disable x64 mode and clone XLA at HEAD)
      JAXCI_SETUP_TEST_ENVIRONMENT: 1
      JAXCI_HERMETIC_PYTHON_VERSION: "3.10"

    steps:
      - uses: actions/checkout@v3
      # Halt for testing
      - name: Wait For Connection
        uses: ./actions/ci_connection/
      - name: Run Bazel CPU Tests
        env:
          ENV_FILE: ci/envs/run_tests/bazel_cpu
        run: ./ci/run_bazel_test_cpu.sh
