name: Run Bazel CPU tests with RBE

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        runner: ["windows-x86-n2-64", "linux-x86-n2-64", "linux-arm64-t2a-48"]

    runs-on: ${{ matrix.runner }}
    container: ${{ (contains(matrix.runner, 'linux-x86') && 'us-central1-docker.pkg.dev/tensorflow-sigs/tensorflow/build:670606426-python3.12') ||
                   (contains(matrix.runner, 'linux-arm64') && 'us-central1-docker.pkg.dev/tensorflow-sigs/tensorflow/linux-arm64-arc-container:latest') ||
                   (contains(matrix.runner, 'windows-x86') && null) }}

    env:
      # Disable running `run_docker_container.sh`. JAX self-hosted runners already run in a Docker
      # container.
      JAXCI_RUN_DOCKER_CONTAINER: 0
      JAXCI_HERMETIC_PYTHON_VERSION: "3.12"

    steps:
      - uses: actions/checkout@v3
      # Halt for testing
      - name: Wait For Connection
        uses: ./actions/ci_connection/
      - name: Run Bazel CPU Tests
        run: ./ci/run_bazel_test.sh "ci/envs/run_tests/bazel_cpu"
