name: Run Bazel GPU tests (RBE)

on:
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        runner: ["linux-x86-g2-48-l4-4gpu"]

    runs-on: ${{ matrix.runner }}
    container:
      image: "gcr.io/tensorflow-testing/nosla-cuda12.3-cudnn9.1-ubuntu20.04-manylinux2014-multipython:latest"

    env:
      # Do not run Docker container for Linux runners. Linux runners already run in a Docker container.
      JAXCI_RUN_DOCKER_CONTAINER: 0
      JAXCI_CLONE_MAIN_XLA: 1
      JAXCI_HERMETIC_PYTHON_VERSION: 3.12

    steps:
      - uses: actions/checkout@v3
      # Halt for testing
      - name: Wait For Connection
        uses: google-ml-infra/actions/ci_connection@main
        id: wait-for-connection
      - name: Nvidia smi
        run: |
          trap 'PYTHONUNBUFFERED=1 python ${{ steps.wait-for-connection.outputs.halt-trap-script }} --shell-command "$BASH_COMMAND"; exit $?' ERR
          nvidia-smi
      - name: Run Bazel GPU tests using RBE
        run: ./ci/run_bazel_test.sh "ci/envs/run_tests/bazel_gpu_rbe.env"
