name: Run Bazel GPU tests (RBE)

on:
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      halt-for-connection:
        description: 'Should this workflow run wait for a remote connection?'
        type: choice
        required: true
        default: 'no'
        options:
        - 'yes'
        - 'no'

jobs:
  build:
    strategy:
      matrix:
        runner: ["linux-x86-n2-16"]

    runs-on: ${{ matrix.runner }}
    container:
      image: "us-central1-docker.pkg.dev/tensorflow-sigs/tensorflow/ml-build:latest"

    env:
      JAXCI_CLONE_MAIN_XLA: 1
      JAXCI_HERMETIC_PYTHON_VERSION: 3.12

    steps:
      - uses: actions/checkout@v3
      # Halt for testing
      - name: Wait For Connection
        uses: google-ml-infra/actions/ci_connection@main
        with:
          halt-dispatch-input: ${{ inputs.halt-for-connection }}
      - name: Run Bazel GPU tests using RBE
        run: ./ci/run_bazel_test_gpu_rbe.sh
