name: Run Bazel GPU tests (non RBE)

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        runner: ["linux-x86-g2-48-l4-4gpu"]

    runs-on: ${{ matrix.runner }}
    container:
      image: "gcr.io/tensorflow-testing/nosla-cuda12.3-cudnn9.1-ubuntu20.04-manylinux2014-multipython:latest"

    env:
      # GitHub actions run in Docker by defaut. Disable running the `setup_docker.sh` script.
      JAXCI_RUN_DOCKER_CONTAINER: 0
      JAXCI_CLONE_MAIN_XLA: 1
      JAXCI_HERMETIC_PYTHON_VERSION: 3.11

    steps:
      - uses: actions/checkout@v3
      # Halt for testing
      - name: Wait For Connection
        uses: ./actions/ci_connection/
      - name: Build jaxlib
        run: ./ci/build_artifacts.sh "ci/envs/build_artifacts/jaxlib.env"
      - name: Build jax-cuda-plugin
        run: ./ci/build_artifacts.sh "ci/envs/build_artifacts/jax-cuda-plugin.env"
      - name: Build jax-cuda-pjrt
        run: ./ci/build_artifacts.sh "ci/envs/build_artifacts/jax-cuda-pjrt.env"
      - name: Run Bazel GPU tests locally
        run: ./ci/run_bazel_test.sh "ci/envs/run_tests/bazel_gpu_non_rbe.env"
      - name: Test if step runs
        run: echo "This step ran!"
