name: Build JAX Artifacts

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runner: ["windows-x86-n2-64"] #, "linux-x86-n2-64", "linux-arm64-t2a-48"]
        artifact: ["jaxlib"] #["jax", "jaxlib", "jax-cuda-pjrt", "jax-cuda-plugin"]
        python: ["3.10"] #["3.10", "3.11", "3.12"]
        # jax-cuda-pjrt and jax are pure Python packages so they do not need to be built for each
        # Python version.
        # exclude:
        #   - artifact: "jax-cuda-pjrt"
        #     python: "3.10"
        #   - artifact: "jax-cuda-pjrt"
        #     python: "3.11"
        #   - artifact: "jax"
        #     python: "3.10"
        #   - artifact: "jax"
        #     python: "3.11"

    runs-on: ${{ matrix.runner }}
    # container:
    #  image: ${{ (contains(matrix.runner, 'linux-x86') && 'us-central1-docker.pkg.dev/tensorflow-sigs/tensorflow/build:670606426-python3.9') || (contains(matrix.runner, 'linux-arm64') && 'us-central1-docker.pkg.dev/tensorflow-sigs/tensorflow/build-arm64:jax-') }}
      # Only Linux runners suppport Docker-in-Docker mode.
    #  if: ${{ (contains(matrix.runner, 'linux') }}

    env:
      JAXCI_SETUP_DOCKER: 0
      # Use RBE to build the artifacts.
      JAXCI_BUILD_ARTIFACT_WITH_RBE: 0

    steps:
      - uses: actions/checkout@v3
      # Halt for testing
      - name: Wait For Connection
        uses: ./actions/ci_connection/
      - name: Build ${{ matrix.artifact }}
        # Explicitly set the shell to bash to override the default Windows environment, i.e, cmd.
        shell: bash
        env:
          JAXCI_HERMETIC_PYTHON_VERSION: "${{ matrix.python }}"
        run: ./ci/build_artifacts.sh ${{ matrix.artifact }}