name: Build Jaxlib

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        runner: ["arc-linux-x86-n2-64"]

    runs-on: ${{ matrix.runner }}
    container:
      image: "index.docker.io/tensorflow/build@sha256:7fb38f0319bda36393cad7f40670aa22352b44421bb906f5cf34d543acd8e1d2"

    env:
      ENV_FILE: ci/envs/build_artifacts/jaxlib/linux_x86/py312
      JAXCI_RUN_IN_ACTIONS: 1

    steps:
      - uses: actions/checkout@v3
      # Halt for connection if workflow dispatch is told to or if it is a retry with the label halt_on_retry
      - name: Wait For Connection
        uses: ./actions/ci_connection/
        with:
          halt-dispatch-input: ${{ inputs.halt-for-connection }}
      - name: Run build script
        run: ./ci/build_artifacts.sh