name: Build JAX Artifacts

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runner: ["linux-x86-n2-64", "linux-arm64-t2a-48"]
        artifact: ["jax", "jaxlib", "jax-cuda-pjrt", "jax-cuda-plugin"]
        python: ["3.10", "3.11", "3.12"]
        # jax-cuda-pjrt and jax are pure Python packages so they do not need to be built for each
        # Python version.
        #
        exclude:
          - artifact: "jax-cuda-pjrt"
            python: "3.10"
          - artifact: "jax-cuda-pjrt"
            python: "3.11"
          - artifact: "jax"
            python: "3.10"
          - artifact: "jax"
            python: "3.11"

    runs-on: ${{ matrix.runner }}
    container:
      image: ${{ (contains(matrix.runner, 'linux-x86') && 'index.docker.io/tensorflow/build@sha256:e042f39c18a01012349ad42ae69f6c9fb6e8cc912ddf362d47f6caf1f97f54c3') || (contains(matrix.runner, 'linux-arm64') && 'us-central1-docker.pkg.dev/tensorflow-sigs/tensorflow/build-arm64:jax-latest-multi-python') }}

    env:
      JAXCI_USE_DOCKER: 0
      JAXCI_USE_RBE: 1

    steps:
      - uses: actions/checkout@v3
      # Halt for testing
      - name: Wait For Connection
        uses: ./actions/ci_connection/
      - name: Install missing docker dependencies
        run: python3 -m pip install build auditwheel
      - name: Build ${{ matrix.artifact }}
        env:
          JAXCI_HERMETIC_PYTHON_VERSION: "${{ matrix.python }}"
        run: ./ci/build_artifacts.sh ${{ matrix.artifact }}