name: Build JAX Artifacts

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runner: ["arc-linux-x86-n2-64"]
        artifact: ["jaxlib", "jax-cuda-pjrt", "jax-cuda-plugin"]
        # Include python only for artifacts that need it
        include:
          - artifact: "jaxlib"
            python: ["3.10", "3.11", "3.12"]
          - artifact: "jax-cuda-plugin"
            python: ["3.10", "3.11", "3.12"]
          - artifact: "jax-cuda-pjrt"
            python: ["3.12"]

    runs-on: ${{ matrix.runner }}
    container:
      image: "index.docker.io/tensorflow/build@sha256:e042f39c18a01012349ad42ae69f6c9fb6e8cc912ddf362d47f6caf1f97f54c3"

    env:
      JAXCI_USE_DOCKER: 0
      JAXCI_USE_RBE: 1

    steps:
      - uses: actions/checkout@v3
      # Halt for testing
      - name: Wait For Connection
        uses: ./actions/ci_connection/
      - name: Build ${{ matrix.artifact }}
        env:
          JAXCI_HERMETIC_PYTHON_VERSION: "${{ matrix.python }}"
        run: ./ci/build_artifacts.sh ${{ matrix.artifact }}