name: Build Jaxlib

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        runner: ["arc-linux-x86-n2-64"]
        container:
          - image: "index.docker.io/tensorflow/build@sha256:7fb38f0319bda36393cad7f40670aa22352b44421bb906f5cf34d543acd8e1d2"

    runs-on: ${{ matrix.runner }}

    env:
      ENV_FILE: ci/envs/build_artifacts/jaxlib/linux_x86/py312

    steps:
      - uses: actions/checkout@v3
      - name: Run build script
        run: ./ci/build_artifacts.sh