name: Culprit Finder Workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  bisect-step:
    uses: ./.github/workflows/hello_world.yml
    name: Call the Reusable CI Workflow