name: Docker Test Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'release/**'

jobs:
  run_tests:
    runs-on: "linux-x86-n2-16-quoct"
    container: "google/cloud-sdk:524.0.0"
    name: "Test build container"
# End Presubmit Naming Check github-cpu-presubmits
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Sleep
        run: sleep 10000
      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.23.0
          driver: remote
          endpoint: tcp://localhost:1234
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./test_docker
          push: true
          tags: us-central1-docker.pkg.dev/tensorflow-sigs/tensorflow/quoct-test-build:latest
