name: Hello World
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}

permissions: {}

jobs:
  hello_world_job:
    runs-on: linux-arm64-t2a-16
    container: 'us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build-arm64:latest'
    steps:
- name: Say hello
  run: echo "Hello, world"
