name: Hello World
on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # allows triggering the workflow run manually
  workflow_call:

permissions: {}

jobs:
  build:
    
    runs-on: linux-arm64-t2a-16
    container: 'us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build-arm64:latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Simulate build
        run: |
          echo "Building the project..."
          sleep 10
          echo "Build complete."

  test:
    runs-on: linux-arm64-t2a-16
    container: 'us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build-arm64:latest'
    needs: build # This job depends on the 'build' job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Intermediate step
        run: |
          echo "Running tests......"
          sleep 15
          echo "Tests complete."
      - name: Simulate testing
        run: |
          echo "Running tests......."
          sleep 15
          echo "Tests complete."