name: JAX Array API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      halt-for-connection:
        description: 'Should this workflow run wait for a remote connection?'
        type: choice
        required: true
        default: 'yes'
        options:
          - 'yes'
          - 'no'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  build:
    runs-on: linux-x86-ct4p-240-4tpu
    strategy:
      matrix:
        python-version: [3.11]
    env:
      PYTHON: "python${{ matrix.python-version }}"
    steps:
    - name: Checkout jax
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      with:
        persist-credentials: false
    - uses: actions/setup-python@v6
      with:
        python-version: '3.11' 
    - name: Install TPU
      run: python -m pip install jax[tpu] -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
    - name: Test
      run: python -c "import jax; print(jax.devices())"
