name: JAX Array API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: linux-x86-n2-16
    container: us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build:infrastructure-public-image-2d2a7b1e6e2e
    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
      with:
        python-version: 3.11
    - name: Use the value
      id: step_two
      run: |
        printf '%s\n' "$action_state" # This will output 'yellow'
    - name: Report success or failure as github status
      if: always()
      shell: bash
      run: sleep 10000
