name: JAX Array API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: linux-x86-g2-16-l4-1gpu-quoct
    container: us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build:infrastructure-public-image-2d2a7b1e6e2e
    steps:
    - name: Set the value
      id: step_one
      run: |
        echo "action_state=yellow" >> "$GITHUB_ENV"
        sleep 1000
    - name: Use the value
      id: step_two
      run: |
        printf '%s\n' "$action_state" # This will output 'yellow'
    - name: Report success or failure as github status
      if: always()
      shell: bash
      run: sleep 10000
