name: Run Pytest GPU tests

# on:
#   pull_request:
#     branches:
#       - main

jobs:
  build:
    strategy:
      matrix:
        runner: ["linux-x86-g2-48-l4-4gpu"]
        python: ["3.10"]

    runs-on: ${{ matrix.runner }}
    container:
      image: "gcr.io/tensorflow-testing/nosla-cuda12.3-cudnn9.1-ubuntu20.04-manylinux2014-multipython:latest"

    env:
      # GitHub actions run in Docker by defaut. Disable running the `setup_docker.sh` script.
      JAXCI_SETUP_DOCKER: 0
      # Use RBE to build the artifacts.
      JAXCI_BUILD_ARTIFACT_WITH_RBE: 1
      # Setup the test environment (disable x64 mode and clone XLA at HEAD)
      JAXCI_SETUP_TEST_ENVIRONMENT: 1
      JAXCI_HERMETIC_PYTHON_VERSION: ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v3
      # Halt for testing
      - name: Wait For Connection
        uses: ./actions/ci_connection/
      - name: Build jaxlib
        run: ./ci/build_artifacts.sh jaxlib
      - name: Build jax-cuda-plugin
        run: ./ci/build_artifacts.sh jax-cuda-plugin
      - name: Build jax-cuda-pjrt
        run: ./ci/build_artifacts.sh jax-cuda-pjrt
      - name: Install pytest
        env:
          JAXCI_PYTHON: python${{ matrix.python }}
        run: $JAXCI_PYTHON -m pip install pytest
      - name: Install dependencies
        env:
          JAXCI_PYTHON: python${{ matrix.python }}
        run: $JAXCI_PYTHON -m pip install -r build/test-requirements.txt
      - name: Run Pytest GPU tests
        env:
          ENV_FILE: ci/envs/run_tests/pytest_gpu
        run: ./ci/run_pytest.sh
