name: Run Pytest CPU tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        runner: ["linux-x86-n2-64"]
        python: ["3.10"]

    runs-on: ${{ matrix.runner }}
    container:
      image: "gcr.io/tensorflow-testing/nosla-cuda12.3-cudnn9.1-ubuntu20.04-manylinux2014-multipython:latest"

    env:
      JAXCI_USE_DOCKER: 0
      JAXCI_USE_RBE: 1
      JAXCI_RUN_TESTS: 1
      JAXCI_CLONE_MAIN_XLA: 1
      JAXCI_HERMETIC_PYTHON_VERSION: ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v3
      # Halt for testing
      - name: Wait For Connection
        uses: ./actions/ci_connection/
      - name: Build jaxlib
        run: ./ci/build_artifacts.sh jaxlib
      - name: Install pytest
        env:
          JAXCI_PYTHON: python${{ matrix.python }}
        run: $JAXCI_PYTHON -m pip install pytest
      - name: Install dependencies
        env:
          JAXCI_PYTHON: python${{ matrix.python }}
        run: $JAXCI_PYTHON -m pip install -r build/test-requirements.txt
      - name: Run Pytest CPU tests
        env:
          ENV_FILE: ci/envs/run_tests/pytest_cpu
        run: ./ci/run_pytest.sh
