name: CI - Pytest CPU

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    defaults:
      run:
        # Explicitly set the shell to bash to override the default Windows environment, i.e, cmd.
        shell: bash

    strategy:
        fail-fast: false # don't cancel all jobs on failure
        matrix:
          runner: ["linux-x86-t2a-48-dev",]
          python: ["3.10",]
          enable-x64: [1, 0]

    runs-on: ${{ matrix.runner }}
    container: "us-central1-docker.pkg.dev/tensorflow-sigs/tensorflow/ml-build-arm64:latest"

    name: "Pytest CPU (${{ matrix.runner }}, Python ${{ matrix.python }}, x64=${{ matrix.enable-x64 }})"

    env:
      JAXCI_HERMETIC_PYTHON_VERSION: "${{ matrix.python }}"
      JAXCI_PYTHON: "python${{ matrix.python }}"
      JAXCI_ENABLE_X64: ${{ matrix.enable-x64 }}

    
    steps:
      - uses: actions/checkout@v3
      # Halt for testing
      - name: Wait For Connection
        uses: google-ml-infra/actions/ci_connection@main
      # Checkout XLA at head, if we're building jaxlib at head.
      - name: Checkout XLA at head
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          repository: openxla/xla
          path: xla
      # We need to mark the GitHub workspace as safe as otherwise git commands will fail.
      - name: Mark GitHub workspace as safe
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Set PLATFORM env var for use in artifact download URL
        run: |
            $JAXCI_PYTHON build/build.py build --wheels=jaxlib \
                        --bazel_options=--config=rbe_linux_x86_64 \
                        --local_xla_path="$(pwd)/xla" \
                        --verbose
      - name: Install dependencies
        run: $JAXCI_PYTHON -m pip install -r build/requirements.in
      - name: Run Pytest CPU tests
        run: ./ci/run_pytest_cpu.sh