name: Run Pytest GPU tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      halt-for-connection:
        description: 'Should this workflow run wait for a remote connection?'
        type: choice
        required: true
        default: 'no'
        options:
        - 'yes'
        - 'no'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build_artifacts:
    name: "Build the jaxlib and CUDA aritfacts with latest XLA"
    uses: ./.github/workflows/build_artifacts.yml      
    strategy:
        fail-fast: false # don't cancel all jobs on failure
        matrix:
          runner: ["linux-x86-n2-16"]
          artifact: ["jaxlib", "jax-cuda-plugin", "jax-cuda-pjrt"]
          python: ["3.10",] # "3.11", "3.12", "3.13"]
    with:
      runner: ${{ matrix.runner }}
      artifact: ${{ matrix.artifact }}
      python: ${{ matrix.python }}
      clone_main_xla: 1
      upload_artifacts: true
      upload_destination_prefix: '${{ github.workflow }}/${{ github.run_number }}/${{ github.run_attempt }}'

  run_tests:
    needs: build_artifacts
    strategy:
      fail-fast: false # don't cancel all jobs on failure
      matrix:
        test_env: [
          {cuda_version: "12.3", runner: "linux-x86-g2-48-l4-4gpu", 
          image: "us-central1-docker.pkg.dev/tensorflow-sigs/tensorflow/nosla-cuda12.3-cudnn9.1-ubuntu20.04-manylinux2014-multipython:latest"},
          {cuda_version: "12.1", runner: "linux-x86-g2-48-l4-4gpu", 
          image: "us-central1-docker.pkg.dev/tensorflow-sigs/tensorflow/nosla-cuda12.1-cudnn9.1-ubuntu20.04-manylinux2014-multipython:latest"},
          ]
        python: ["3.10"]
        enable-x_64: [1, 0]

    runs-on: ${{ matrix.test_env.runner }}
    container:
      image: ${{ matrix.test_env.image }}
    
    name: "Pytest GPU (${{ matrix.test_env.runner }}, CUDA ${{ matrix.test_env.cuda_version }}, Python ${{ matrix.python }}, x64=${{ matrix.enable-x_64 }})"

    env:
      JAXCI_HERMETIC_PYTHON_VERSION: ${{ matrix.python }}
      JAXCI_ENABLE_X64: ${{ matrix.enable-x_64 }}

    steps:
      - uses: actions/checkout@v3
      # Halt for testing
      - name: Wait For Connection
        uses: google-ml-infra/actions/ci_connection@main
        with:
          halt-dispatch-input: ${{ inputs.halt-for-connection }}
      - name: Set Platform
        run: |
          os=$(uname -s | awk '{print tolower($0)}')
          arch=$(uname -m)

          # Adjust name for Windows
          if [[  $os  =~ "msys_nt" ]]; then
            os="windows"

          fi

          echo "PLATFORM=${os}_${arch}" >> $GITHUB_ENV
      - name: Download artifacts built in the "build_artifacts" job
        run: mkdir -p $(pwd)/dist && gsutil -m cp -r gs://general-ml-ci-transient/jax-github-actions/"${{ github.workflow }}"/${{ github.run_number }}/${{ github.run_attempt }}/$PLATFORM/python${JAXCI_HERMETIC_PYTHON_VERSION}/*.whl $(pwd)/dist/
      - name: Install dependencies
        env:
          JAXCI_PYTHON: python${{ matrix.python }}
        run: $JAXCI_PYTHON -m pip install -r build/requirements.in
      - name: Run Pytest GPU tests
        run: ./ci/run_pytest_gpu.sh
