name: Kanglan Real JAX ARM64 Test
on:
  push:
    branches: kanglan/test_arm64

jobs:
  test-real-bazel:
    uses: ./.github/workflows/bazel_cpu.yml
    with:
      runner: "kanglan-linux-arm64-c4a"
      python: "3.12"
      build_jaxlib: "true"
      build_jax: "true"
      bazel_command: "build"

