name: Run Bazel GPU tests locally

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        runner: ["arc-linux-x86-g2-96-l4-8gpu"]

    runs-on: ${{ matrix.runner }}
    container:
      image: "index.docker.io/tensorflow/build@sha256:e042f39c18a01012349ad42ae69f6c9fb6e8cc912ddf362d47f6caf1f97f54c3"

    env:
      JAXCI_USE_DOCKER: 0
      JAXCI_USE_RBE: 1
      JAXCI_RUN_TESTS: 1
      JAXCI_HERMETIC_PYTHON_VERSION: 3.11

    steps:
      - uses: actions/checkout@v3
      # Halt for testing
      - name: Wait For Connection
        uses: ./actions/ci_connection/
      - name: Build jaxlib
        run: ./ci/build_artifacts.sh jaxlib
      - name: Build jax-cuda-plugin
        run: ./ci/build_artifacts.sh jax-cuda-plugin
      - name: Build jax-cuda-pjrt
        run: ./ci/build_artifacts.sh jax-cuda-pjrt
      - name: Set ENV_FILE to run Bazel GPU tests locally
        run: export ENV_FILE=ci/run_tests/bazel_local_gpu
      - name: Run Bazel GPU tests locally
        run: ./ci/run_bazel_test_gpu.sh
